main: spider.cpp wolff.cpp latticeOps.cpp testFuncs.cpp wolffRun.cpp wolffHistRun.cpp
	g++ -Wall -std=c++11 -o main.exe spider.cpp wolff.cpp latticeOps.cpp testFuncs.cpp wolffRun.cpp wolffHistRun.cpp -Ithreadpool/boost/ -lboost_system -lboost_thread  -lpthread
