main: spider.cpp wolff.cpp latticeOps.cpp calcQuants.cpp wolffRun.cpp wolffHistRun.cpp ioFuncs.cpp
	g++ -std=c++11 -o main.exe spider.cpp wolff.cpp latticeOps.cpp calcQuants.cpp wolffRun.cpp wolffHistRun.cpp ioFuncs.cpp
