#!/bin/bash

mkdir $PWD/output/parruns/
sleep 1
for i in {1..20}; do
	qsub -t 1-6 -o $PWD/output/parruns/ -p -1 runmain $PWD
	echo $i
	sleep 60
	while [[ $(qstat) = *runmain* ]]; do
		sleep 60
	done
done
for filename in $PWD/output/parruns/*; do
	cat $filename >> $PWD/output/regWolff
done
rm -r $PWD/output/parruns/
python3 $PWD/updMaxE.py
