#!/bin/bash
batchN=4;
mkdir /home/simsan/exjobb/modular/output/parruns/
sleep 2
for i in {1 .. $batchN}; do
	qsub -t 1-12 -o /home/simsan/exjobb/modular/output/parruns/ -p -1 runmain
	sleep 30
	while [[ $(qstat) = *runmain* ]]; do
		sleep 30
	done
done
/home/simsan/exjobb/modular/merge
python3 /home/simsan/exjobb/modular/updMaxE.py
