#!/bin/bash
mkdir $PWD/teqoutput/tempteq/
sleep 1
for i in {1..20}; do
	qsub -t 1-6 -o $PWD/teqoutput/tempteq/ -p -1 runteqdef $PWD
	echo $i
	sleep 5
	while [[ $(qstat) = *run2teqdef* ]]; do
		sleep 5
	done
done
for filename in $PWD/teqoutput/tempteq/*; do
	cat $filename >> $PWD/teqoutput/newTeqRun
done
rm -r $PWD/teqoutput/tempteq/
